add script to compare and merge terms from data model to cv table
mc2-center/data-models-ARCHIVED pull request #16
Opened 2022-09-09 16:53 UTC by brynnz22

I added a script to compare the valid values in the MC2 data model with our [current controlled vocabulary table](https://www.synapse.org/#!Synapse:syn26433610/tables/), and merge the differences.

2022-10-05 21:41 UTC, brynnz22 commented
@vpchung @xindiguo I think this is finally ready for review. I edited it to get rid of some things that won't be applicable on a monthly basis. I also added some capitalization conversions for the output.

2022-10-11 00:16 UTC, vpchung requested changes

2022-10-11 00:16 UTC, vpchung commented on scripts/cv_data_model_match.py
> +    parser.add_argument('table_id',
Do positional arguments allow for default values?  I feel like the `table_id` value wouldn't change that often, so I'd recommend doing a default value if it's available!

2022-10-11 00:16 UTC, vpchung commented on scripts/cv_data_model_match.py
> +        '[None]', '').str.strip("[|]|'").replace(r'^\s*$', np.nan, regex=True)
Nice approach!

Here's another solution (that may be simpler?):

```
cv_df['nonpreferredTerms'] = cv_df['nonpreferredTerms'].str.join(", ").replace("", np.nan)
```

where:

* `.str.join(", ")` does the same as `.map(str).replace('[None]', '').str.strip("[|]|'")`
* `.replace("", np.nan)` does the same as `.replace(r'^\s*$', np.nan, regex=True)`

2022-10-11 00:16 UTC, vpchung commented on scripts/cv_data_model_match.py
> +            if choice == 'y':
For robustness, you could do something like:

```
if choice.lower().startswith('y'):
   ...
```

so that if a user enters "Y" or "yes", it will still get accepted.

You could also use the `re` approach, for faster performance:

```
import re
...

if bool(re.match(r"y", choice, re.I)):
   ...
```

2022-10-11 00:16 UTC, vpchung commented on scripts/cv_data_model_match.py
> +                continue
I don't think this `continue` is needed?  Since there are no other commands to run after this block, it will already move onto the next iteration of the loop.

2022-10-11 00:16 UTC, vpchung commented on scripts/cv_data_model_match.py
> +    if bool(dm_add) == True:
It's not Pythonic to do comparions with `True`/`False`, e.g. `... == True` or `... == False`.  Rather, you should simply do this instead:

```
if dm_add:
```

since an empty dictionary is considered "falsey":

```
>>> dm_add = {}
>>> if dm_add:
...     "not empty"
... else:
...     "empty"
... 
'empty'
```

2022-10-11 00:16 UTC, vpchung commented on scripts/cv_data_model_match.py
> +        exit()
I don't think this `exit()` is necessary.

2022-10-12 23:26 UTC, brynnz22 commented on scripts/cv_data_model_match.py
> +    parser.add_argument('table_id',
Thank you! I changed it to optional arguments and added this!

2022-10-12 23:27 UTC, brynnz22 commented on scripts/cv_data_model_match.py
> +        '[None]', '').str.strip("[|]|'").replace(r'^\s*$', np.nan, regex=True)
That looks way better! Thanks!

2022-10-12 23:27 UTC, brynnz22 commented on scripts/cv_data_model_match.py
> +            if choice == 'y':
I didn't know I could do this!

2022-10-12 23:27 UTC, brynnz22 commented on scripts/cv_data_model_match.py
> +                continue
Great! Deleted it.

2022-10-12 23:27 UTC, brynnz22 commented on scripts/cv_data_model_match.py
> +    if bool(dm_add) == True:
This is good to know :)

2022-10-12 23:27 UTC, brynnz22 commented on scripts/cv_data_model_match.py
> +        exit()
Also deleted it!

2022-10-13 00:03 UTC, vpchung requested changes

2022-10-13 00:03 UTC, vpchung commented on scripts/cv_data_model_match.py
> +                        action='store',
This is the default behavior for [`action`](https://docs.python.org/3/library/argparse.html#action), so no need to specify this.

```suggestion
```

2022-10-13 00:03 UTC, vpchung commented
One last minor change, then I think it's good.

Nicely done!

2022-10-17 15:58 UTC, brynnz22 commented
Thank you! I changed this!

2022-10-17 17:05 UTC, vpchung approved these changes

2022-10-17 19:10 UTC, merged